version: '3.8'

services:
  mysqldb:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: dbsql
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    healthcheck:
      test: ['CMD', 'mysql', '-u$DB_USERNAME', '-p$DB_PASSWORD']
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - apisql
  backend:
    build: .
    depends_on:
      mysqldb:
        condition: service_healthy
    container_name: backend
    env_file: .env
    environment:
      - MYSQL_HOST=$DB_HOST
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    ports:
      - '3333:3333'
    expose:
      - 3333
    command: npm run dev
    networks:
      - apisql

networks:
  apisql:
    driver: bridge

